First draft of the deployment script
ArkCase/ark_deploy_old pull request #1
Opened 2021-08-06 09:59 UTC by fabricetriboix

Important notes:
  1. I am not too happy about how this script works, especially regarding how it deals with secrets
  2. The deployment script might be superseded by CDK for Kubernetes, should we choose to go this route

So in essence: The code in this PR is not really satisfactory and might be dumped in the near future anyway.

2021-08-06 18:25 UTC, JonHolman requested changes

2021-08-06 18:25 UTC, JonHolman commented on deploy.py
> +        print(f"DEBUG: {msg}", flush=True)
please look into establishing a logger and log to it, like:
`
import logging
logger: logging.Logger = logging.getLogger(__name__)
`

2021-08-06 18:25 UTC, JonHolman commented on deploy.py
> +    time.sleep(2)
is there a way we can poll to see if any our terminating?  If so, loop until they're done?

2021-08-09 09:05 UTC, fabricetriboix commented on deploy.py
> +        print(f"DEBUG: {msg}", flush=True)
@JonHolman I thought this was an overkill for such a simple script. Do you really want me to use the `logging` module?

2021-08-09 16:57 UTC, JonHolman commented on deploy.py
> +        print(f"DEBUG: {msg}", flush=True)
you can hold off until we decide if we're going to stick with this approach.  If we stay with this eventually we will want to.

2021-08-09 20:11 UTC, fabricetriboix commented on deploy.py
> +    time.sleep(2)
@JonHolman Apologies, but I don't understand your comment...

2021-08-09 21:12 UTC, JonHolman commented on deploy.py
> +    time.sleep(2)
Can we poll kubernetes to see if any pods are currently terminating?  If so, I was thinking like:
`while pods_pending_termination():
    time.sleep(1)
`

2021-08-10 08:21 UTC, fabricetriboix commented on deploy.py
> +    time.sleep(2)
Sure, I can do something like that. What would be the purpose of this?

2021-08-10 18:03 UTC, JonHolman commented on deploy.py
> +    time.sleep(2)
I was thinking instead of:
`# Wait for the controller to potentially terminate existing pods
    time.sleep(2)`

2021-08-10 18:51 UTC, fabricetriboix commented on deploy.py
> +    time.sleep(2)
Could you please provide me with an example or two of when such a thing could be used? Sorry if I'm a bit thick, I would like to understand the use case(s) for what you are suggesting. Maybe there is something I missed or don't understand...

2021-08-13 09:45 UTC, fabricetriboix commented on deploy.py
> +    time.sleep(2)
@JonHolman ping

2021-08-13 10:06 UTC, naveen-armedia requested changes

2021-08-13 10:06 UTC, naveen-armedia commented on files/activemq-generic-persistent-volume-claim.yaml.j2
> +      storage: "{{ activemq_data_size_GB }}G"
@fabricetriboix I think before we running deploy script we should also define `stroageclass.yaml` for EBS and EFS. So if we want to run the deploy script over `eks` platform we could refer to the same  `storageclass`  name in PVC yaml file . Also in  this jinja2 template, we could have the condition that if the platform is `eks` then use `storageClassName` to the appropriate storageclass name defined in storageclass.yaml

2021-08-13 10:12 UTC, fabricetriboix commented on files/activemq-generic-persistent-volume-claim.yaml.j2
> +      storage: "{{ activemq_data_size_GB }}G"
The question is: Should this script be able to run on EKS before we consider this task done?

As a reminder, this task was to port the deploy script I did in the DevOps repo and add ActiveMQ. The objective, as far as I understood it, was to be able to deploy locally (eg: minikube) so I could make a presentation and the team can have an idea of how it would work, and also such that you can understand what I meant by keeping the PVC outside the Helm chart.

As per my general comment, I am not too happy with the way the script work, but I think the goal above has been achieved and this PR can be closed. If we want to make this script perfect before closing this PR, I'm afraid it will take a long time, and all that work might very well be for nothing if we decide to switch to CDK for Kubernetes.

So I would be disinclined to work on any additional feature for this script at this stage, but work only on bugfix and/or documentation.

2021-08-13 10:40 UTC, naveen-armedia commented on files/activemq-generic-persistent-volume-claim.yaml.j2
> +      storage: "{{ activemq_data_size_GB }}G"
@fabricetriboix what are the exact goals we want to achieve with this script.?  I assumed this script is a standard way to deploy on all the platforms because when you showed the demo in the last meeting you showed a `platform` variable with `eks`, `minikube` like that.  Are there any plans to use this script for EKS deployments..?

2021-08-13 10:45 UTC, fabricetriboix commented on files/activemq-generic-persistent-volume-claim.yaml.j2
> +      storage: "{{ activemq_data_size_GB }}G"
That is the eventual goal of the script, but not the goal of this task/PR. Again, we might decide not to use this script but instead use CDK for Kubernetes. So I do not want to spend hours/days making it work to perfection, and all this work is wasted if we decide to use CDK for Kubernetes.

The definition of "done" for this task is the one I gave above, and I consider this task is done, unless there are bugs to fix or things to document.

2021-08-13 10:46 UTC, fabricetriboix commented on files/activemq-generic-persistent-volume-claim.yaml.j2
> +      storage: "{{ activemq_data_size_GB }}G"
If we decide to use this script rather than CDK for Kubernetes, only then we will work on it to make it work on EKS

2021-08-13 10:53 UTC, naveen-armedia commented on files/activemq-generic-persistent-volume-claim.yaml.j2
> +      storage: "{{ activemq_data_size_GB }}G"
Alright okay.

2021-08-13 18:14 UTC, JonHolman commented on deploy.py
> +    time.sleep(2)
@fabricetriboix  I'm sorry.  I missed your previous comment.  I think we should discuss this.

2021-08-13 18:18 UTC, JonHolman commented on deploy.py
> +    time.sleep(2)
Where you have:

```
    # Wait for the controller to potentially terminate existing pods
    time.sleep(2)
```

I am proposing we instead do something like:

```
    while pods_pending_termination(): 
        time.sleep(1)
```

instead of arbitrarily having it sleep for 2 seconds and hoping the pending terminations are complete.  Of course we would have to figure out how to check if anything is still pending termination.

2021-08-13 18:47 UTC, merged